### ISSUE TITLE
Feature: EigenPods able to receive arbitrary Ether

### ISSUE THREAD

**Issue by mattstam** [Layr-Labs/eigenlayer-contracts#77]
## Background
An [EigenPod](https://github.com/Layr-Labs/eigenlayer-contracts/blob/fb97cf40ef963a5b66246b4f77a95d724eb5cd53/src/contracts/pods/EigenPod.sol#L35) are cannot currently receive ETH via normal EVM execution. The fact that EigenPods can currently accept ETH from withdrawals is due to the fact that this type of transfer occurs [outside of EVM execution](https://github.com/ethereum/go-ethereum/blob/d40a255e973775575d8d16456252f93ac75c09f0/consensus/beacon/consensus.go#L353).

## Problem
There exists many scenarios in which the withdrawal credentials are used as a reference to forward rewards to a validator. When the withdrawal credentials are an EOA, this works fine. But when this is a contract account, the contract must have a `receive()` and/or `fallback()` exposed, for example:

```Solidity
    receive() external payable {}

    fallback() external payable {}
```

Since EigenPods do not have this, any attempt to transfer ETH via EVM transaction execution will revert.

## Use-Cases

Example: [MEV](https://docs.prylabs.network/docs/execution-node/fee-recipient) rewards from running [mev-boost](https://docs.prylabs.network/docs/execution-node/fee-recipient) with your validator, and setting the [fee recipient](https://docs.prylabs.network/docs/execution-node/fee-recipient) as your withdrawal address.

Example: [Nouns](https://nouns.wtf/) [raffle](https://prop.house/nouns/open-round-20/6036) where if a validator has `⌐◨-◨` in their graffiti, they are eligible to be awarded with ETH. The ETH is sent directly to the withdrawal address.

There are an unknown number of future circumstances in which a validator may be eligible for rewards. As these cases grow, having a payable withdrawal address becomes even more important.

## Proposal

Add:
```Solidity
receive() external payable {}
```
along with functionality for EigenPod owners to withdraw (or restake) this ETH.

**Comment by gpsanant** [comment]
Hey @mattstam , thanks for the issue.

In the next launch of EigenPods, native restakers will be able to prove that partial withdrawals and full withdrawals occurred and be able to withdraw funds from their pod accordingly. As of now, partial withdrawals are not restaked on EigenLayer and are instantly withdrawn to the DelayedWithdrawalRouter (which sends funds to the pod owners after a safety delay). Full withdrawals remain in the pod since they back the stake on EigenLayer. They are only withdrawn when the pod owner withdraws from EigenLayer.

The problem setting ones fee recipient to an EigenPod or the cool noundao use case is the pod can never know whether the funds are due to a full withdrawal and therefore cannot be withdrawn because they may be backing EigenLayer stake.

EigenPods will are planned to move to an optimistic system where users claim that they have proven all of their full withdrawals before a certain block number and then, after a dispute period, are able to withdraw the excess funds in their pod at that time. After that upgrade occurs, something like this is totally possible, but for the current version this would lead to a temporary freezing of funds.

If you have any ideas on how the next proofs based launch could be amended to support this, it would be great to consider them.

**Comment by ctian1** [comment]
Since withdrawals (as far as I'm aware) don't occur like normal ETH transfers, they shouldn't call the receive function. So shouldn't we be able to add logic to the receive function (like incrementing a balance variable) so that we can keep track of the excess non-beaconchain rewards/deposits?

**Comment by gpsanant** [comment]
got it. you are totally right! @Sidu28 does this work with you?

**Comment by mattstam** [comment]
I also think having a `sweep()` function for ERC20 balances on the EigenPod contract would be valuable and not collide with existing functionality. 

Rationale is the same as OP: there are an unknown number of future circumstances in which a validator may be eligible for rewards, and the most obvious place to send them to is their withdrawal address.

**Comment by ChaoticWalrus** [comment]
Apologies for not commenting on this thread sooner.

We've discussed this some offline, going to summarize thoughts:

- the proposal for a `receive` function that simply increments some withdrawable amount by the `msg.value` seems safe + sane -- as I understand it, this would help specifically with MEV-boost integration, as proposers are paid using a standard ETH-call transfer, rather than being specified as the 'fee recipient' of the block
- an ERC20 sweep that the pod owner can call also seems fine to add
- EigenPods still shouldn't be specified as the `fee recipient` of a block; since these transfers work like self-destructs / validator withdrawals, we won't have an easy way to tell these apart from transfers as the result of a validator withdrawal

**Comment by ChaoticWalrus** [comment]
This was addressed in by a commit https://github.com/Layr-Labs/eigenlayer-contracts/commit/77a1597d7f58938300abbacb709deca2a45a8642 that has been merged into the master branch. We expect to roll out the feature addition as part of the next upgrade to contracts. Please reopen this issue if the feature addition doesn't meet your needs!

**Comment by mattstam** [comment]
The code provided has a re-entrancy vulnerability:
```Solidity
       AddressUpgradeable.sendValue(payable(recipient), amountToWithdraw);
       nonBeaconChainETHBalanceWei -= amountToWithdraw;
```
I think this is fixed in main though, just a heads-up to do the upgrade from a post-fix commit.

**Comment by ChaoticWalrus** [comment]
> The code provided has a re-entrancy vulnerability:
> 
> ```solidity
>        AddressUpgradeable.sendValue(payable(recipient), amountToWithdraw);
>        nonBeaconChainETHBalanceWei -= amountToWithdraw;
> ```
> 
> I think this is fixed in main though, just a heads-up to do the upgrade from a post-fix commit.

Ah yeah, thanks lol. This was indeed caught and fixed.
